"""presence_memory_projects"""

import sqlalchemy as sa

from alembic import op

revision = "0004"
down_revision = "0003"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "presence_sessions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("connected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_heartbeat_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_activity_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("disconnected_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("presence_sessions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_presence_sessions_user_id"), ["user_id"], unique=False)

    op.create_table(
        "presence_tickets",
        sa.Column("digest", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("digest"),
    )
    with op.batch_alter_table("presence_tickets", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_presence_tickets_user_id"), ["user_id"], unique=False)

    op.create_table(
        "projects",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_projects_user_id"), ["user_id"], unique=False)

    op.create_table(
        "memories",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=True),
        sa.Column("category", sa.String(length=24), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("importance", sa.Integer(), nullable=False),
        sa.Column("source_chat_id", sa.String(length=36), nullable=True),
        sa.Column("source_message_id", sa.String(length=36), nullable=True),
        sa.Column("is_pinned", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("use_count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["source_chat_id"], ["chats.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["source_message_id"], ["messages.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("memories", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_memories_category"), ["category"], unique=False)
        batch_op.create_index(batch_op.f("ix_memories_is_active"), ["is_active"], unique=False)
        batch_op.create_index(batch_op.f("ix_memories_is_pinned"), ["is_pinned"], unique=False)
        batch_op.create_index(batch_op.f("ix_memories_project_id"), ["project_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_memories_user_id"), ["user_id"], unique=False)

    op.create_table(
        "message_contexts",
        sa.Column("message_id", sa.String(length=36), nullable=False),
        sa.Column("memory_ids", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["message_id"], ["messages.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("message_id"),
    )
    if op.get_bind().dialect.name == "sqlite":
        op.execute("ALTER TABLE chats ADD COLUMN project_id VARCHAR(36) REFERENCES projects(id)")
    else:
        op.add_column(
            "chats",
            sa.Column(
                "project_id",
                sa.String(36),
                sa.ForeignKey("projects.id", name="fk_chats_project"),
                nullable=True,
            ),
        )
    op.create_index("ix_chats_project_id", "chats", ["project_id"])
    op.add_column(
        "users", sa.Column("display_name", sa.String(80), server_default="Пользователь", nullable=False)
    )
    op.add_column("users", sa.Column("custom_instructions", sa.Text(), server_default="", nullable=False))
    op.add_column("users", sa.Column("use_memory", sa.Boolean(), server_default="1", nullable=False))
    op.add_column("users", sa.Column("relevant_memory", sa.Boolean(), server_default="1", nullable=False))
    op.add_column("users", sa.Column("max_memories", sa.Integer(), server_default="12", nullable=False))
    op.add_column(
        "users",
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default="1970-01-01 00:00:00", nullable=False
        ),
    )
    op.execute("UPDATE users SET updated_at = created_at")

    # ### end Alembic commands ###


def downgrade():
    # Remove dependent new tables before altering existing data-bearing tables.
    op.drop_table("message_contexts")
    op.drop_table("memories")
    op.drop_index("ix_chats_project_id", table_name="chats")
    if op.get_bind().dialect.name == "sqlite":
        op.execute("ALTER TABLE chats DROP COLUMN project_id")
    else:
        op.drop_constraint("fk_chats_project", "chats", type_="foreignkey")
        op.drop_column("chats", "project_id")
    op.drop_table("projects")
    op.drop_table("presence_tickets")
    op.drop_table("presence_sessions")
    for column in (
        "display_name",
        "custom_instructions",
        "use_memory",
        "relevant_memory",
        "max_memories",
        "updated_at",
    ):
        op.drop_column("users", column)
