"""web_tools"""

import sqlalchemy as sa

from alembic import op

revision = "0007"
down_revision = "0006"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tool_preferences",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("values", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "tool_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("chat_id", sa.String(length=36), nullable=False),
        sa.Column("generation_id", sa.String(length=36), nullable=True),
        sa.Column("tool_name", sa.String(length=80), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("risk_level", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("input_summary", sa.JSON(), nullable=False),
        sa.Column("input_digest", sa.String(length=64), nullable=False),
        sa.Column("cost_estimate", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("cost_actual", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("provider_run_id", sa.String(length=160), nullable=True),
        sa.Column("error_code", sa.String(length=80), nullable=True),
        sa.Column("result_metadata", sa.JSON(), nullable=False),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["chat_id"], ["chats.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["generation_id"], ["messages.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("tool_runs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_tool_runs_chat_id"), ["chat_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_tool_runs_generation_id"), ["generation_id"], unique=False)
        batch_op.create_index("ix_tool_runs_owner_started", ["user_id", "started_at"], unique=False)

    op.create_table(
        "web_source_snapshots",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("generation_id", sa.String(length=36), nullable=False),
        sa.Column("tool_run_id", sa.String(length=36), nullable=False),
        sa.Column("label", sa.String(length=12), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("final_url", sa.Text(), nullable=False),
        sa.Column("title", sa.String(length=400), nullable=False),
        sa.Column("excerpt", sa.Text(), nullable=False),
        sa.Column("publisher", sa.String(length=300), nullable=True),
        sa.Column("published_at", sa.String(length=80), nullable=True),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("searched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("etag", sa.String(length=300), nullable=True),
        sa.Column("last_modified", sa.String(length=100), nullable=True),
        sa.ForeignKeyConstraint(["generation_id"], ["messages.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tool_run_id"], ["tool_runs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("web_source_snapshots", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_web_source_snapshots_user_id"), ["user_id"], unique=False)
        batch_op.create_index("ix_web_sources_generation_label", ["generation_id", "label"], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("web_source_snapshots", schema=None) as batch_op:
        batch_op.drop_index("ix_web_sources_generation_label")
        batch_op.drop_index(batch_op.f("ix_web_source_snapshots_user_id"))

    op.drop_table("web_source_snapshots")
    with op.batch_alter_table("tool_runs", schema=None) as batch_op:
        batch_op.drop_index("ix_tool_runs_owner_started")
        batch_op.drop_index(batch_op.f("ix_tool_runs_generation_id"))
        batch_op.drop_index(batch_op.f("ix_tool_runs_chat_id"))

    op.drop_table("tool_runs")
    op.drop_table("tool_preferences")
    # ### end Alembic commands ###
