//! Desktop-owned restore (upgrade safety slice).
//!
//! A restore must never run against a live server: the Desktop stops its **owned** backend,
//! runs the same sidecar binary in its one-shot `--restore-backup <dir>` mode (which
//! verifies the backup, keeps a safety copy of the current state, stages and swaps the
//! database and documents), and then starts the backend again.
//!
//! Rules enforced here:
//! * only a directory inside this installation's `backups/` root with a `manifest.json`
//!   can be restored — no arbitrary paths, no traversal, no symlinks;
//! * an external developer backend is never stopped, so the command refuses instead;
//! * no secret is read, written or logged; the restore result is a small JSON report.

use std::path::{Path, PathBuf};
use std::process::Command;
use std::time::{Duration, Instant};

use serde_json::{json, Value};

use crate::backend::{self, BackendState, Ownership, RuntimeMode};

const RESTORE_TIMEOUT_SECONDS: u64 = 600;
const RESULT_FILE: &str = "backup-restore.json";

/// Backup ids are generated by the backend (`<stamp>-<kind>`); anything else is refused.
pub fn valid_backup_id(value: &str) -> bool {
    !value.is_empty()
        && value.len() <= 96
        && value
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || matches!(c, '-' | '_' | '.'))
        && !value.starts_with('.')
}

/// Windows `canonicalize` returns a verbatim path (`\\?\C:\…`). Another process (the
/// Python helper) receives it as an argument and would build an invalid SQLite URI from it,
/// so the prefix is removed here as well as tolerated there.
fn plain_path(path: PathBuf) -> PathBuf {
    let text = path.to_string_lossy().to_string();
    if let Some(rest) = text.strip_prefix(r"\\?\") {
        if let Some(unc) = rest.strip_prefix("UNC\\") {
            return PathBuf::from(format!(r"\\{unc}"));
        }
        return PathBuf::from(rest);
    }
    if let Some(rest) = text.strip_prefix("//?/") {
        return PathBuf::from(rest);
    }
    path
}

/// Resolve a backup directory that is guaranteed to live inside `<data root>/backups`.
pub fn resolve_backup_dir(root: &Path, backup_id: &str) -> Result<PathBuf, String> {
    if !valid_backup_id(backup_id) {
        return Err("backup_id_invalid".into());
    }
    let backups = root.join("backups");
    let backups = backups
        .canonicalize()
        .map_err(|_| "backup_missing".to_string())?;
    let candidate = backups.join(backup_id);
    if candidate.is_symlink() {
        return Err("backup_unsafe_path".into());
    }
    let resolved = candidate
        .canonicalize()
        .map_err(|_| "backup_missing".to_string())?;
    if !resolved.starts_with(&backups) || resolved == backups {
        return Err("backup_unsafe_path".into());
    }
    if !resolved.is_dir() {
        return Err("backup_missing".into());
    }
    let manifest = resolved.join("manifest.json");
    if manifest.is_symlink() || !manifest.is_file() {
        return Err("backup_incomplete".into());
    }
    Ok(plain_path(resolved))
}

fn sidecar_command(directory: &Path) -> Result<Command, String> {
    let root = backend::data_root();
    let (program, cwd, mode) = backend::backend_launch()?;
    let secret = backend::load_or_create_jwt(&root)?;
    if secret.len() < 48 || secret.contains('\n') {
        return Err("JWT_SECRET_FAILED".into());
    }
    let token = backend::load_or_create_runtime_token(&root).unwrap_or_default();
    let mut command = Command::new(&program);
    command.current_dir(&cwd);
    if mode != RuntimeMode::Packaged {
        command.args(["-m", "app.runtime_entry"]);
    }
    command.args(["--restore-backup", &directory.to_string_lossy()]);
    command.env("PYTHONUNBUFFERED", "1");
    backend::base_backend_env(&mut command, &mode, &root, &secret, &token);
    command
        .stdin(std::process::Stdio::null())
        .stdout(std::process::Stdio::null())
        .stderr(std::process::Stdio::null());
    #[cfg(windows)]
    {
        use std::os::windows::process::CommandExt;
        const CREATE_NO_WINDOW: u32 = 0x0800_0000;
        const CREATE_UNICODE_ENVIRONMENT: u32 = 0x0000_0400;
        command.creation_flags(CREATE_NO_WINDOW | CREATE_UNICODE_ENVIRONMENT);
    }
    Ok(command)
}

fn read_report(root: &Path) -> Option<Value> {
    let path = root.join("runtime").join(RESULT_FILE);
    let text = std::fs::read_to_string(path).ok()?;
    serde_json::from_str::<Value>(&text).ok()
}

fn report_text(report: Option<&Value>, key: &str) -> String {
    report
        .and_then(|value| value.get(key))
        .and_then(Value::as_str)
        .unwrap_or("")
        .to_string()
}

/// Restore one backup while the Desktop owns the lifecycle. A typed result is returned for
/// every outcome; the command only errors when the request itself is impossible.
#[tauri::command]
pub async fn restore_backup(backup_id: String) -> Result<Value, String> {
    tauri::async_runtime::spawn_blocking(move || restore_backup_blocking(&backup_id))
        .await
        .map_err(|error| error.to_string())?
}

pub fn restore_backup_blocking(backup_id: &str) -> Result<Value, String> {
    let root = backend::data_root();
    let directory = match resolve_backup_dir(&root, backup_id) {
        Ok(path) => path,
        Err(code) => {
            return Ok(json!({
                "restored": false,
                "code": code,
                "message": message_for(&code),
            }))
        }
    };

    // An external backend is not ours: never stop it, never restore under it.
    let status = backend::stop_backend_blocking()?;
    if status.ownership == Ownership::External {
        return Ok(json!({
            "restored": false,
            "code": "backend_external",
            "message": "Локальный сервер запущен вне Alex. Остановите его и повторите восстановление.",
        }));
    }
    if status.state == BackendState::Error {
        // The stop itself failed (e.g. the port never freed): do not touch the database.
        let code = status.error.unwrap_or_else(|| "backend_stop_failed".into());
        return Ok(json!({
            "restored": false,
            "code": code,
            "message": "Локальный сервер не остановился. Закройте Alex и повторите.",
        }));
    }

    let mut command = match sidecar_command(&directory) {
        Ok(command) => command,
        Err(code) => {
            let restarted = backend::ensure_backend_blocking().ok();
            return Ok(json!({
                "restored": false,
                "code": code,
                "message": message_for(&code),
                "backend": restarted,
            }));
        }
    };

    let run = command.spawn();
    let (exit_code, report) = match run {
        Ok(mut child) => {
            let deadline = Instant::now() + Duration::from_secs(RESTORE_TIMEOUT_SECONDS);
            let code = loop {
                match child.try_wait() {
                    Ok(Some(status)) => break status.code().unwrap_or(-1),
                    Ok(None) => {
                        if Instant::now() >= deadline {
                            // Bounded: a stuck restore must not freeze the app forever. The
                            // helper writes nothing until it finishes, so the database and its
                            // safety copy are still on disk either way.
                            let _ = child.kill();
                            let _ = child.wait();
                            break -1;
                        }
                        std::thread::sleep(Duration::from_millis(200));
                    }
                    Err(_) => break -1,
                }
            };
            (code, read_report(&root))
        }
        Err(_) => (-1, None),
    };
    let restarted = backend::ensure_backend_blocking().ok();

    let restored = report
        .as_ref()
        .and_then(|value| value.get("restored"))
        .and_then(Value::as_bool)
        .unwrap_or(false);
    let code = if restored {
        String::new()
    } else {
        let code = report_text(report.as_ref(), "code");
        if code.is_empty() {
            "restore_failed".to_string()
        } else {
            code
        }
    };
    let message = if restored {
        "Данные восстановлены из резервной копии.".to_string()
    } else {
        let message = report_text(report.as_ref(), "message");
        if message.is_empty() {
            message_for(&code)
        } else {
            message
        }
    };

    Ok(json!({
        "restored": restored,
        "code": code,
        "message": message,
        "backup_id": backup_id,
        "safety_backup_id": report_text(report.as_ref(), "safety_backup_id"),
        "to_revision": report_text(report.as_ref(), "to_revision"),
        "documents": report.as_ref().and_then(|value| value.get("documents")).cloned().unwrap_or(Value::Null),
        "at": report_text(report.as_ref(), "at"),
        "exit_code": exit_code,
        "backend": restarted,
    }))
}

fn message_for(code: &str) -> String {
    match code {
        "backup_id_invalid" => "Некорректный идентификатор резервной копии.".into(),
        "backup_missing" => "Резервная копия не найдена.".into(),
        "backup_incomplete" => "Резервная копия неполная: нет описания или базы.".into(),
        "backup_unsafe_path" => "Путь резервной копии ведёт за пределы папки резервных копий.".into(),
        "backup_corrupt" => "Резервная копия повреждена.".into(),
        "backup_tampered" => "Резервная копия изменена после создания.".into(),
        "backup_unsupported_format" => "Формат резервной копии не поддерживается этой версией Alex.".into(),
        "restore_busy" => "Локальная база занята. Закройте Alex и повторите.".into(),
        "insufficient_disk_space" => "Недостаточно места на диске для восстановления.".into(),
        "JWT_SECRET_FAILED" => "Не удалось подготовить локальный ключ входа.".into(),
        "BACKEND_SIDECAR_MISSING" => "Не найден встроенный сервер. Переустановите Alex LLM.".into(),
        _ => "Не удалось восстановить резервную копию.".into(),
    }
}

/// Non-secret information the panel may show: where backups live and how many exist.
#[tauri::command]
pub fn backup_location() -> Value {
    let root = backend::data_root();
    let backups = root.join("backups");
    let count = std::fs::read_dir(&backups)
        .map(|entries| {
            entries
                .filter_map(Result::ok)
                .filter(|entry| entry.path().join("manifest.json").is_file())
                .count()
        })
        .unwrap_or(0);
    json!({
        "root": backups.to_string_lossy(),
        "exists": backups.is_dir(),
        "count": count,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    fn temp_root(name: &str) -> PathBuf {
        let path = std::env::temp_dir().join(format!("alex-backup-{}-{}", name, std::process::id()));
        let _ = std::fs::remove_dir_all(&path);
        std::fs::create_dir_all(path.join("backups")).unwrap();
        path
    }

    #[test]
    fn backup_ids_are_conservative() {
        assert!(valid_backup_id("20260921T101500Z-manual"));
        assert!(valid_backup_id("20260921T101500Z-pre_upgrade-2"));
        for bad in ["", "../etc", "..", "a/b", "a\\b", "C:", ".hidden", "with space"] {
            assert!(!valid_backup_id(bad), "{bad} must be refused");
        }
    }

    #[test]
    fn verbatim_paths_are_made_plain_for_other_processes() {
        assert_eq!(
            plain_path(PathBuf::from(r"\\?\C:\Users\Alex LLM\backups\x")),
            PathBuf::from(r"C:\Users\Alex LLM\backups\x")
        );
        assert_eq!(
            plain_path(PathBuf::from(r"\\?\UNC\server\share\x")),
            PathBuf::from(r"\\server\share\x")
        );
        let plain = PathBuf::from(r"C:\keep\this");
        assert_eq!(plain_path(plain.clone()), plain);
    }

    #[test]
    fn only_directories_inside_the_backups_root_are_accepted() {
        let root = temp_root("resolve");
        let inside = root.join("backups").join("20260921T101500Z-manual");
        std::fs::create_dir_all(&inside).unwrap();
        std::fs::write(inside.join("manifest.json"), "{}").unwrap();
        assert_eq!(
            resolve_backup_dir(&root, "20260921T101500Z-manual").unwrap(),
            plain_path(inside.canonicalize().unwrap())
        );

        // No manifest: not a backup.
        let empty = root.join("backups").join("20260921T101501Z-manual");
        std::fs::create_dir_all(&empty).unwrap();
        assert_eq!(
            resolve_backup_dir(&root, "20260921T101501Z-manual").unwrap_err(),
            "backup_incomplete"
        );

        // Traversal and absolute paths never resolve.
        for bad in ["..", "../..", "C:/Windows", "../../Windows"] {
            assert!(resolve_backup_dir(&root, bad).is_err(), "{bad} must be refused");
        }
        // The backups root itself is not a backup.
        assert_eq!(resolve_backup_dir(&root, ".").unwrap_err(), "backup_id_invalid");
        let _ = std::fs::remove_dir_all(&root);
    }

    #[test]
    fn a_missing_backups_directory_is_reported_as_missing() {
        let root = std::env::temp_dir().join(format!("alex-backup-none-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&root);
        std::fs::create_dir_all(&root).unwrap();
        assert_eq!(resolve_backup_dir(&root, "20260921T101500Z-manual").unwrap_err(), "backup_missing");
        let _ = std::fs::remove_dir_all(&root);
    }

    #[test]
    fn restore_messages_have_no_stack_traces_or_secrets() {
        for code in [
            "backup_corrupt",
            "backup_tampered",
            "restore_busy",
            "unknown-code",
        ] {
            let message = message_for(code);
            assert!(!message.contains("Traceback"), "{code}");
            assert!(!message.to_lowercase().contains("jwt"), "{code}");
            assert!(!message.to_lowercase().contains("key"), "{code}");
            assert!(!message.is_empty());
        }
    }

    #[test]
    fn the_result_report_is_read_from_the_runtime_directory() {
        let root = temp_root("report");
        std::fs::create_dir_all(root.join("runtime")).unwrap();
        std::fs::write(
            root.join("runtime").join(RESULT_FILE),
            r#"{"restored": true, "backup_id": "x", "safety_backup_id": "y"}"#,
        )
        .unwrap();
        let report = read_report(&root).unwrap();
        assert_eq!(report["restored"], true);
        assert_eq!(report_text(Some(&report), "safety_backup_id"), "y");
        assert_eq!(report_text(None, "safety_backup_id"), "");
        let _ = std::fs::remove_dir_all(&root);
    }

    #[test]
    fn restore_never_touches_a_credential_target() {
        // The restore path works on files only: it has no credential read or write, so it
        // cannot clone machine identity. The scope builder itself stays valid.
        let target = crate::credential::scoped_target("gateway", "installation").unwrap();
        assert!(target.starts_with("Alex LLM/"));
    }
}
